import Head from "next/head";
// import Image from "next/image";
import Script from "next/script";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <style jsx global>
        {`
          .myImg {
            border-radius: 50%;
            margin: 10px;
            width: 150px;
            height: 150px;
          }
          h2 {
            font-size: 2rem;
            margin: 10px 0px;
          }
          h3 {
            font-size: 1.25rem;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="hunting coder, coder blog, problem solver" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='sc.js' strategy='lazyOnload' /> */}
      <main className={styles.main}>
        <Image className="myImg" src="/home.jpg" alt={"Image Not Found"} width="237" height="145" />
        {/* <img className="myImg" src="./home.jpg" alt="Image Not Found" width="237" height="145" /> */}
        <div>
          <h1 className={styles.title}>&lt;Hunting Code/&gt;</h1>
        </div>
        <div>
          <h2>Latest Blogs</h2>
          <div className={styles.blogItem}>
            <h3>How to learn javascript in 2022?</h3>
            <p className={styles.blogDesc}>Javascript is the language use to design logic for the web.</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javascript in 2022?</h3>
            <p className={styles.blogDesc}>Javascript is the language use to design logic for the web.</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javascript in 2022?</h3>
            <p className={styles.blogDesc}>Javascript is the language use to design logic for the web.</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className={styles.blogItem}>
            <h3>How to learn javascript in 2022?</h3>
            <p className={styles.blogDesc}>Javascript is the language use to design logic for the web.</p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>
    </>
  );
}
